// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopicalFruitKnockoff.Models;

namespace TopicalFruitKnockoff.Migrations
{
    [DbContext(typeof(FrootsContext))]
    [Migration("20190306002508_secondMigration")]
    partial class secondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TopicalFruitKnockoff.Models.Catagory", b =>
                {
                    b.Property<int>("CatagoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Desctiption");

                    b.Property<string>("ImgUrl");

                    b.Property<string>("Name");

                    b.HasKey("CatagoryId");

                    b.ToTable("Catagories");

                    b.HasData(
                        new { CatagoryId = 1, Desctiption = "These are smoothies", ImgUrl = "Testing", Name = "Smoothies" }
                    );
                });

            modelBuilder.Entity("TopicalFruitKnockoff.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CatagoryId");

                    b.Property<string>("Description");

                    b.Property<string>("ImgUrl");

                    b.Property<string>("Name");

                    b.Property<int?>("OrderId");

                    b.Property<double>("Price");

                    b.HasKey("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("Items");

                    b.HasData(
                        new { ItemId = 1, CatagoryId = 1, Description = "Mangoos", ImgUrl = "Testing", Name = "Mango", Price = 2.0 }
                    );
                });

            modelBuilder.Entity("TopicalFruitKnockoff.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("OrderId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("TopicalFruitKnockoff.Models.Item", b =>
                {
                    b.HasOne("TopicalFruitKnockoff.Models.Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
